### ISSUE TITLE
我想在最上一个栏目加上菜单栏目，怎么实现啊

### ISSUE THREAD

**Issue by xx-zhang** [Tencent/tdesign-common#1188]
### 这个功能解决了什么问题

多菜单分割，而不是一个菜单列出所有的nav

### 你建议的方案是什么

无

**Comment by uyarn** [comment]
没理解你的问题 可以截个图或者给个codesandbox吗

**Comment by xx-zhang** [comment]
> 没理解你的问题 可以截个图或者给个codesandbox吗

@uyarn 
类似腾讯云的控制台，上方有很多个nav, 切换CVM、域名解析等服务时候，左侧的收缩菜单栏里面的内容会变化。
