### ISSUE TITLE
表单内输入框样式规范不一致

### ISSUE THREAD

**Issue by brucemeteor** [Tencent/tdesign-common#1493]
**TDesign-vue-next 1.3.9版本中，为什么 input-number 要定死一个固定width，而input却定义的是width:100%？**

- input-number组件宽度
https://github.com/Tencent/tdesign-common/blob/d5d8b2e24723526fbd09cbfe742afe948260ccea/style/web/components/input-number/_index.less#L24
- input组件的宽度
https://github.com/Tencent/tdesign-common/blob/d5d8b2e24723526fbd09cbfe742afe948260ccea/style/web/components/input/_index.less#L16

这样不一致的行为
1. 行为不一致，让人觉得组件无法统一很疑惑，
2. 带来了额外的CSS处理负担，因为表单样式宽度不一了
<img width="421" alt="image" src="https://github.com/Tencent/tdesign-common/assets/26224399/7191fd13-6b09-4fb3-913d-2fb00d53b7eb">

**示例Demo如下**
```html
<t-form>
    <t-form-item label="贷款金额" name="amount">
      <t-input-adornment append="元">
        <t-input-number large-number theme="normal" :format="formatLargeNumber" placeholder="请输入内容"/>
      </t-input-adornment>
    </t-form-item>
    <t-form-item label="贷款年限" name="loanTerm">
      <t-input-adornment append="月">
        <t-input placeholder="请输入内容"/>
      </t-input-adornment>
    </t-form-item>
    <t-form-item label="贷款年利率" name="loanRate">
      <t-input-adornment append="%">
        <t-input placeholder="请输入内容"/>
      </t-input-adornment>
    </t-form-item>
    <t-form-item label="还款方式" name="rePaymentMethod">
      <t-radio-group default-value="equalPrincipal">
        <t-radio value="equalPrincipal">等额本金</t-radio>
        <t-radio value="equalInstallment">等额本息</t-radio>
      </t-radio-group>
    </t-form-item>
  </t-form>
```

**Comment by chaishi** [comment]
这是个好问题，可能最初只是为了限制一个 min-width

**Comment by brucemeteor** [comment]
> 这是个好问题，可能最初只是为了限制一个 min-width

嗯.... 看来要追溯历史确实是个麻烦事，那就不深究了

建议`input-number`组件能够遵循和 `input`组件一样的宽度选项
