### ISSUE TITLE
[小白提问] 为什么中文字符算2个长度，而英文字符算1个长度？

### ISSUE THREAD

**Issue by brucemeteor** [Tencent/tdesign-common#1647]
### tdesign-common 版本

无

### 重现步骤

https://github.com/Tencent/tdesign-common/blob/e82c00ea8b279d5d7d8b122068c129ddc63e64ff/js/utils/helper.ts#L103-L137

阅读源代码一直很奇怪，为什么不使用  String.length方法来判断长度，而是特意判断了英文中文，这里面的深意是？

**Comment by algerkong** [comment]
这里获取的是字节长度，英文字母是一个字节，中文一个字是占用两个字节
