### ISSUE TITLE
[upload] 单词拼写错误

### ISSUE THREAD

**Issue by pyongchen** [Tencent/tdesign-common#1685]
### tdesign-common 版本

1.0.0

### 重现链接

https://github.com/Tencent/tdesign-common/blob/develop/js/global-config/locale/en_US.ts

### 重现步骤

拖动文件到拖拽框
![image](https://github.com/Tencent/tdesign-common/assets/14769708/e91198e8-bd55-41fc-b1a1-f2003891d9be)

### 期望结果

Drop here

### 实际结果

Drop hear

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-common/pull/1686
