### ISSUE TITLE
InputNumber 组件，聚焦状态缺少蓝色边框样式

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-common#179]
- InputNumber 聚焦时，缺少蓝色边框
- InputNumer 禁用时，文本颜色和其他组件不一样

![image](https://user-images.githubusercontent.com/11605702/150632562-8ca675ba-ed94-4430-b3d2-bd40d2137c80.png)

![image](https://user-images.githubusercontent.com/11605702/150634925-958660c7-0f07-42a3-95bf-ccaf2272ab0f.png)

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
