### ISSUE TITLE
[menu] Unexpected whitespace :not( .t-is-disabled)

### ISSUE THREAD

**Issue by Atox724** [Tencent/tdesign-common#1799]
### tdesign-common 版本

dev

### 重现步骤

menu/_index.less：line 592
`    &:hover:not(.@{prefix}-is-active):not(.@{prefix}-is-opened):not(
    .@{prefix}-is-disabled
  ) {
      background-color: @menu-item-hover-bg--light;
    }
`

### 期望结果

不要因为换行导致的多余空格, 会导致打包时 css-syntax爆出警告
```
▲ [WARNING] Unexpected whitespace [css-syntax-error]

    <stdin>:6876:60:
      6876 │ ...hover:not(.t-is-active):not(.t-is-opened):not( .t-is-disabled) {
           ╵                                                  ^
```

**Comment by uyarn** [comment]
方便的话可以直接提交PR修复
