### ISSUE TITLE
Switch 组件，关闭状态背景颜色和设计稿不一致

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-common#180]
![image](https://user-images.githubusercontent.com/11605702/150632459-e89ec642-033f-42e9-8d59-5bc66550c339.png)

![image](https://user-images.githubusercontent.com/11605702/150629937-38f969ab-090e-449a-8a97-27048845b4c4.png)

![image](https://user-images.githubusercontent.com/11605702/150629941-ccd346ad-4fe0-4c54-9f3e-df351c2a7c92.png)

**Comment by uyarn** [comment]
样式问题 统一transfer到common

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
