### ISSUE TITLE
时间选择器的样式层级问题

### ISSUE THREAD

**Issue by backrunner** [Tencent/tdesign-common#181]
hover样式的层级高于蓝色部分，这个是符合预期的设计吗？感觉有一些奇怪。
在hover被激活的情况下稍微滚动多一点就能看到一个灰色的色块跟着数字一起滑上去，体验不是很好。

![image](https://user-images.githubusercontent.com/12205593/150675858-91e8029f-5568-4cc9-bfb1-4992051c60d4.png)

https://tdesign.tencent.com/vue-next/components/time-picker

官网的demo就可以用来测试。

**Comment by uyarn** [comment]
React 已修改timepicker样式及交互 https://github.com/Tencent/tdesign-react/pull/559
<img width="405" alt="image" src="https://user-images.githubusercontent.com/26377630/167335580-37970f1a-6116-4e7d-8294-b9dd0c1dc742.png">

**Comment by uyarn** [comment]
- [ ] Vue
- [ ] VueNext
