### ISSUE TITLE
input组件的placeholder文字颜色不对

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-common#188]
**Describe Framework**

tdesign-vue、tdesign-vue-next、tdesign-react

**Describe Environment**

Chrome 97.0.4692.99 (x86_64)

**Describe the bug**
 input组件的placeholder文字颜色不对，目前使用的是text-color-secondary，应该要使用text-color-placeholder
![image](https://user-images.githubusercontent.com/89069385/150956113-1953a83b-9230-4f52-bc0d-9e9992a56d8e.png)

**Comment by xiaosansiji** [comment]
已在 0.34.0 版本中修复
