### ISSUE TITLE
[Feature Request] Menu 添加 `auto` 主题模式/或者默认自适应主题

### ISSUE THREAD

**Issue by WingLim** [Tencent/tdesign-common#189]
## 背景说明

现在的 Menu 组件的 `theme` 属性有两个选项：

1. light
2. dark

在不指定的默认情况下，Menu 的样式是 light，而 TDesign 现在支持了以 variable 为基础的主题模式
Vue 版本举例：https://tdesign.tencent.com/vue/dark-mode

通过设置 `theme-mode` 属性并不能同步切换 Menu 组件的 light/dark 模式，需要给 Menu 组件的 `theme` 属性再额外绑定一个变量进行处理，比较麻烦。

### 方案 1

给 `theme` 属性添加一个 `auto` 模式，这个模式下的 color 相关的样式通过 variable 来设置

### 方案 2

Menu 组件默认样式通过 variable 设置，有指定 light/dark 主题需求的可以通过 `theme` 来手动设置

**Comment by honkinglin** [comment]
个人比较倾向方案1，给 theme 添加 auto 后也可以有两种实现方式
1：css方式的话也可以通过添加 `theme-auto` 类名，配合 `@media (prefers-colo-scheme: dark) {}` 去支持  （觉得比较合理）
2：也可以组件初始化时候 js 获取再去设置对应的 `theme="dark"` or `theme="light"` （需要处理下 ssr 判断）

**Comment by LeeJim** [comment]
其实方案 2 是最低成本，也是最容易实现的方案。
后面应该会采用方案 2 来实现。
