### ISSUE TITLE
Radio 在4K屏幕下选中时选中点没在中心

### ISSUE THREAD

**Issue by yuzunyue** [Tencent/tdesign-common#192]
**Describe Framework**

tdesign-vue

**Describe Environment**

Chrome 97.0.4692.99

**Describe the bug**
Radio 在4K屏幕下选中时选中点没在中心，1080P缩小页面使用放大镜也可复现此BUG

**Additional context**
<img width="328" alt="729207c1f6ab62500e1242034c50a69" src="https://user-images.githubusercontent.com/32872977/150939410-2fd22cae-8e20-43f2-ba62-39125f55fda3.png">
![image](https://user-images.githubusercontent.com/32872977/150939667-0978f1e5-2d23-49e3-b458-9ea583a2afc0.png)

**Comment by uyarn** [comment]
话说好像不局限什么显示器 这个操作都会导致变形..

**Comment by bojue** [comment]
@uyarn 
![image](https://user-images.githubusercontent.com/14350577/153384499-36b1b0e6-0fa0-49d1-a5a1-5c557ca69df3.png)
页面缩放情况：left 和top的计算方案应该不合适
