### ISSUE TITLE
[InputNumber] size 为 small，theme 为 column的情况下，右侧表现异常

### ISSUE THREAD

**Issue by PengYYYYY** [Tencent/tdesign-common#367]
### tdesign-react 版本

0.29.0

### 重现链接

https://stackblitz.com/edit/angular-qb3htg?file=src%2Fdemo.jsx

### 重现步骤

<img width="594" alt="image" src="https://user-images.githubusercontent.com/35833812/161018808-aceb9f28-cd0a-4949-95cf-6007ed516aef.png">

**Comment by uyarn** [comment]
之前的设计是 theme = column时 没有size=small ..
<img width="731" alt="image" src="https://user-images.githubusercontent.com/26377630/161020356-278d4f7c-7520-41cf-baf6-03a10fc4097b.png">

**Comment by Wen1kang** [comment]
@uyarn 设计稿在这 https://www.figma.com/file/KInDIZzoxifaKVQ3n5KB8W/?node-id=42459%3A300256
