### ISSUE TITLE
CSS BEM 规范类名调整

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-common#39]
BEM: https://github.com/Tencent/tdesign-common/blob/develop/css-naming.md

**Comment by xiaosansiji** [comment]
Table 表格

 原类名 | 新类名 | 是否已合入 develop |
| -- | -- | -- |
| t-table-row--disabled | t-table__row--disabled | Vue(✅)、React（无）、VueNext（✅） |
| t-table-row--selected | t-table__row--selected | Vue(✅)、React（无）、VueNext（✅） |
| table-body | t-table__body | Vue(x)、React（✅）、VueNext（x) |
| align-center | t-align-center | Vue(x)、React（✅）、VueNext（x) |
| align-left | t-align-left | Vue(x)、React（✅）、VueNext（x) |
| align-right | t-align-right | Vue(x)、React（✅）、VueNext（x) |
| text-ellipsis | t-text-ellipsis | Vue(x)、React（✅）、VueNext（x) |
| t-table-pagination | t-table__pagination | Vue(x)、React（✅）、VueNext（x) |
| t-table-sort-icon | t-table__sort-icon | Vue(x)、React（✅）、VueNext（x)  |
| t-table-double-icons | t-table__double-icons | Vue(x)、React（✅）、VueNext（x) |
| t-table-sort-icon-active | t-table__sort-icon--active | Vue(x)、React（✅）、VueNext（x) |
| t-table-expand-box | t-table__expand-box | Vue(x)、React（✅）、VueNext（x) |
| t-table-sort-icon-active | t-table__sort-icon--active | Vue(x)、React（✅）、VueNext（x) |
| t-table-content | t-table__content | Vue(x)、React（✅）、VueNext（x) |
| t-table-expandable-icon-cell | t-table__expandable-icon-cell | Vue(x)、React（✅）、VueNext（x) |
| t-table-selection-cell | t-table__selection-cell | Vue(x)、React（无）、VueNext（x) |
| t-table--empty | t-table__empty | Vue(x)、React（✅）、VueNext（x) |
| t-table-valign__top | t-table--align-top | Vue(x)、React（✅）、VueNext（x) |
| t-table--loading-async | t-table__async-loading| Vue(✅)、React（✅）、VueNext（x) |
| t-table--loading-status-loading | t-is-loading| Vue(✅)、React（✅）、VueNext（x) |
| t-table--loading-status-load-more | t-is-load-more| Vue(✅)、React（✅）、VueNext（x) |
| t-table-filter-icon | t-table__filter-icon | Vue(x)、React（✅）、VueNext（x) |
| t-table-filter-pop | t-table__filter-pop | Vue(x)、React（✅）、VueNext（x) |
| t-table-filter-pop-content | t-table__filter-pop-content | Vue(x)、React（✅）、VueNext（x) |
| t-table-filter-pop-content__inner | t-table__filter-pop-content-inner | Vue(x)、React（✅）、VueNext（x) |
| t-table-filter-pop-content__button | t-table__filter-pop-content-button | Vue(x)、React（无）、VueNext（x) |
| t-table-content--scrollable-to-left |	t-table__content--scrollable-to-left | Vue(x)、React（✅）、VueNext（x) |
| t-table-content--scrollable-to-right | t-table__content--scrollable-to-right | Vue(x)、React（✅）、VueNext（x) |
| t-table-expanded-cell | t-table__expanded-cell | Vue(x)、React（✅）、VueNext（x) |

**Comment by xiaosansiji** [comment]
Menu 菜单
|原类名|新类名|是否已合入develop|备注|
|--|--|--|--|
|t-menu-group-title|t-menu-group__title|x|
|t-menu-mode__normal|t-menu--normal|x|无用，已移除|
|t-menu-mode__popup|t-menu--popup|x|无用，已移除|

**Comment by xiaosansiji** [comment]
Dropdown 下拉菜单

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-dropdown__menu__column | t-dropdown__menu-column | Vue(✅)、VueNext（✅）、React(✅) |
| t-dropdown__item__content | t-dropdown__item-content | Vue(✅)、VueNext（✅）、React(✅) |
| t-dropdown__item__content_text | t-dropdown__item-text | Vue(✅)、VueNext（✅）、React(✅) |
| has-suffix | t-dropdown--suffix | Vue(✅)、VueNext（✅）、React(✅) |
| children-suffix | t-dropdown__item-icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-dropdown__split | 可移除 | ✅ |

**Comment by xiaosansiji** [comment]
Divider 分割线
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-divider-inner-text | t-divider__inner-text | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Drawer 抽屉

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-drawer-attach | t-drawer--attach | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-left | t-drawer--left | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-right | t-drawer--right | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-top | t-drawer--top | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-bottom | t-drawer--bottom | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-open | t-drawer--open | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-no-mask | t-drawer--without-mask | Vue(✅ )、VueNext（✅）、React(✅) |
| t-drawer-confirm | t-drawer__confirm |Vue（✅ ）、VueNext（✅）、React(✅) |
| t-drawer-cancel | t-drawer__cancel | Vue（[✅ ）、VueNext（✅）、React(✅)|

**Comment by xiaosansiji** [comment]
Pagination 分页
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-pagiantion__btn--prev | t-pagiantion__btn-prev | Vue(✅ )、VueNext（✅）、React(✅) |
| t-pagiantion__btn--next | t-pagiantion__btn-next | Vue(✅ )、VueNext（✅）、React(✅) |
| more-quickprev | 移除 | ✅ |

**Comment by xiaosansiji** [comment]
Dialog 对话框

⚠️ Upload 组件使用 Dialog 组件作为图片效果预览，Dialog 变更时，需同步更新 Upload 组件相关样式

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-dialog-ctx | t-dialog__ctx | Vue(✅)、VueNext（✅）、React(✅) |
| t-dialog-ctx--fixed | t-dialog__ctx--fixed | Vue(✅)、VueNext（✅）、React(✅) |
| t-not-visable | t-is-hidden | Vue(✅)、VueNext（✅）、React(✅) |
| t-dialog-mask | t-dialog__mask | Vue(✅)、VueNext（✅）、React(✅) |
| t-dialog-mask--hidden | t-is-hidden | Vue(✅)、VueNext（✅）、React(✅) |
| t-dialog-confirm | t-dialog__confirm |Vue（✅） |
| t-dialog-cancel | t-dialog__cancel |Vue（✅)|

**Comment by xiaosansiji** [comment]
Message 全局提示
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-message-close | t-message__close | Vue(✅)、VueNext（✅）、React(✅) |
| t-message-list | t-message__list | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Notification 消息通知
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-notification__detail--item | t-notification__detail-item | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Anchor 锚点

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-anchor_line | t-anchor__line | Vue(✅)、React（✅）、VueNext（✅） |
| t-anchor-item | t-anchor__item | Vue(✅)、React（✅）、VueNext（✅） |
| t-anchor-item_link | t-anchor__item-link | Vue(✅)、React（✅）、VueNext（✅） |
| t-anchor-target | t-anchor__target | Vue(✅)、React（✅）、VueNext（✅） |
| cursor-wrapper | t-anchor__line-cursor-wrapper | Vue(✅)、React（✅）、VueNext（✅） |
| cursor | t-anchor__line-cursor | Vue(✅)、React（✅）、VueNext（✅） |
| t-copy | t-anchor__copy | Vue(✅)、React（✅）、VueNext（✅） |

**Comment by xiaosansiji** [comment]
Select 选择器

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-select-wrap | t-select__wrap | VueNext（✅）Vue（✅） |
| t-select-right-icon | t-select__right-icon | VueNext（✅）Vue（✅） |
| t-select-left-icon | t-select__left-icon | VueNext（✅）Vue（✅） |
| t-select-placeholder | t-select__placeholder | VueNext（✅）Vue（✅） |
| t-select-input | t-select__input | VueNext（✅）Vue（✅） |
| t-select-popup-reference | t-select__popup-reference | VueNext（✅）Vue（✅） |
| t-select-dropdown | t-select__dropdown | VueNext（✅）Vue（✅） |
| t-select-empty | t-select__empty | VueNext（✅）Vue（✅） |
| t-select-loading-tips | t-select__loading-tips | VueNext（✅）Vue（✅） |
| t-select-selectedSingle | t-select__single | VueNext（✅）Vue（✅） |
| t-option-group | t-select-option-group | VueNext（✅）Vue（✅） |
| t-option-group__divider | t-select-option-group__divider | VueNext（✅）Vue（✅） |
| t-option-group-header | t-select-option-group__header | VueNext（✅）Vue（✅） |
| t-select-right-icon__clear | t-select__right-icon-clear | VueNext（✅）Vue（✅） |
| t-select-active-icon | t-select__active-icon | VueNext（✅）Vue（✅） |

**Comment by xiaosansiji** [comment]
Slider 滑块

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-slider-contianer | t-slider__container | Vue(✅)、VueNext（✅）、React(✅) |
| t-slider-input-container | t-slider__input-container | Vue(✅)、VueNext（✅）、React(✅) |
| center-line | t-slider__center-line | Vue(✅)、VueNext（✅）、React(✅) |
| t-slide-vertical | t-slide--vertical | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Form 表单

| 组件 | 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|-----|
| Form 组件 | t-form__controls--content | t-form__controls-content | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Badge 徽标
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-badge-static | t-badge--static | Vue(✅)、VueNext（无）、React(✅) |

**Comment by xiaosansiji** [comment]
List 列表
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-list-items | t-list__inner | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Cascader 级联选择器

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-cascader-placeholder | t-cascader__placeholder | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-content | t-cascader__content | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-is-multiple | t-cascader--multiple | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-dropdown | t-cascader__dropdown | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-panel | t-cascader__panel | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu | t-cascader__menu | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item | t-cascader__item | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item--highlight | t-cascader__item--highlight | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-have-icon | t-cascader__item--with-icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-is-leaf | t-cascader__item--leaf | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item__label | t-cascader__item-label | Vue(✅)、VueNext（✅）、React(x) |  
| t-cascader-item__label--filter | t-cascader__item-label--filter | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item__is-empty | t-cascader__empty | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu__seperator | t-cascader__menu-seperator | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu__filter | t-cascader__menu-filter | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-search-input | t-cascader__search-input | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-icon | t-cascader__icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-icon | t-cascader__item-icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-panel | t-cascader__panel | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Cascader 级联选择器

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-cascader-placeholder | t-cascader__placeholder | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-content | t-cascader__content | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-is-multiple | t-cascader--multiple | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-dropdown | t-cascader__dropdown | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-panel | t-cascader__panel | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu | t-cascader__menu | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item | t-cascader__item | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item--highlight | t-cascader__item--highlight | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-have-icon | t-cascader__item--with-icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-is-leaf | t-cascader__item--leaf | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item__label | t-cascader__item-label | Vue(✅)、VueNext（✅）、React(x) |  
| t-cascader-item__label--filter | t-cascader__item-label--filter | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item__is-empty | t-cascader__empty | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu__seperator | t-cascader__menu-seperator | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-menu__filter | t-cascader__menu-filter | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-search-input | t-cascader__search-input | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-icon | t-cascader__icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-item-icon | t-cascader__item-icon | Vue(✅)、VueNext（✅）、React(✅) |
| t-cascader-panel | t-cascader__panel | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Calendar 日历

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-is-now | t-calendar__table-body-cell--now | Vue(✅)、VueNext（✅）、React(✅) |
| t-calendar__table-body-cell-value | t-calendar__table-body-cell-display | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
DatePicker 日期选择

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-date-picker-popup-reference | t-date-picker__popup-reference |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker--container | t-date-picker__container |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-form-controls | 删除 |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker--panels | t-date-picker__panels |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-header | t-date-picker__header |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-header-title | t-date-picker__header-title |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-header__btn | t-date-picker__header-btn |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-header-controller | t-date-picker__header-controller |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-picker-datetime-range | 删除 |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell__wrapper | t-date-picker__cell-wrapper |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-year | t-date-picker--year |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-month | t-date-picker--month |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-date | t-date-picker--date |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-range | t-date-picker--range |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell__text | t-date-picker__cell-text |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker--ranges-show | 删除|Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-picker-presets | t-date-picker__presets |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date | t-date-picker__panel |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--now | t-date-picker__cell--now |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--active | t-date-picker__cell--active |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--disabled | t-date-picker__cell--disabled |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--highlight | t-date-picker__cell--highlight |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--active-start | t-date-picker__cell--active-start |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--active-end | t-date-picker__cell--active-end |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--additional | t-date-picker__cell--additional |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--first-day-of-month | t-date-picker__cell--first-day-of-month |Vue(✅ )、VueNext（✅ ）、React(✅ ) |
| t-date-cell--last-day-of-month | t-date-picker__cell--last-day-of-month |Vue(✅ )、VueNext（✅ ）、React(✅ ) |

**Comment by xiaosansiji** [comment]
Grid 栅格

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-row-start | r-row--start | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-center | r-row--center | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-end | r-row--end | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-space-between | t-row--space-between| Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-space-around | t-row--space-around  | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-top | t-row--top | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-middle | t-row--middle | Vue(✅ )、VueNext（✅）、React(✅) |
| t-row-bottom | t-row--bottom | Vue(✅ )、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Layout 布局

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-layout-has-sider | t-layout--with-sider | Vue(✅ )、VueNext（✅）、React(✅) |
| t-layout--header | t-layout__header | Vue(✅ )、VueNext（✅）、React(✅) |
| t-layout--content | t-layout__content | Vue(✅ )、VueNext（✅）、React(✅) |
| t-layout--sider | t-layout__sider | Vue(✅ )、VueNext（✅ ）、React(✅) |
| t-layout--footer | t-layout__footer | Vue(✅ )、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Popconfirm

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-popconfirm--position-hidden | 移除 | - |
| t-popconfirm__arrow | 移除 | - |
| t-popconfirm--position-bottom | 移除，方位类名全部移除。有 Popup 方位类名即可 | - |
| t-popconfirm--position-bottom-left | 移除 | - |
| t-popconfirm--position-top | 移除 | - |
| t-popconfirm--position-top-left | 移除 | - |
| t-popconfirm--position-left| 移除 | - |
| t-popconfirm--position-bottom| 移除 | - |
| t-popconfirm--position-right| 移除 | - |
| t-popconfirm--position-right-top | 移除 | - |
| t-popconfirm--position-right-bottom | 移除 | - |
| t-popconfirm--position-bottomRight | 移除 | - |
| t-popconfirm--position-topRight | 移除 | - |

**Comment by xiaosansiji** [comment]
Popup

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-popup-content | t-popup__content | React(✅) VueNext（✅）,Vue（✅）|
| t-popup-reference | t-popup__reference | React(✅) VueNext（✅）,Vue（✅）|
| t-popup_animation-enter | t-popup--animation-enter | React(✅) VueNext（✅）,Vue（✅）|
| t-popup_animation-enter-from | t-popup--animation-enter-from | React(✅)VueNext（✅）,Vue（✅）|
| t-popup_animation-exiting | t-popup--animation-exiting | React(✅)VueNext（✅）,Vue（✅） |
| t-popup_animation-leave-to | t-popup--animation-leave-to | React(✅)VueNext（✅） ,Vue（✅）|
| t-popup_animation-enter-to | t-popup--animation-enter-to | React(✅)VueNext（✅）,Vue（✅） |
| t-popup_animation-entering | t-popup--animation-entering | React(✅)VueNext（✅）,Vue（✅） |
| t-popup_animation-leave-from | t-popup--animation-leave-from | React(✅) VueNext（✅）,Vue（✅）|
| t-popup_animation-leave | t-popup--animation-leave | React(✅) VueNext（✅）,Vue（✅）|
| t-popup_animation-enter-active | t-popup--animation-enter-active | React(✅)VueNext（✅）,Vue（✅） |
| t-popup_animation-leave-active | t-popup--animation-leave-active | React(✅)VueNext（✅）,Vue（✅） |

**Comment by xiaosansiji** [comment]
Tooltip

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-tooltip-light | t-tooltip--light | React(✅) VueNext（✅）,Vue（✅）|
| t-tooltip-default | t-tooltip--default | React(✅) VueNext（✅）,Vue（✅）|
| t-tooltip-primary | t-tooltip--primary | React(✅) VueNext（✅）,Vue（✅）|
| t-tooltip-success | t-tooltip--success | React(✅) VueNext（✅）,Vue（✅）|
| t-tooltip-danger | t-tooltip--danger | React(✅) VueNext（✅）,Vue（✅）|
| t-tooltip-warning | t-tooltip--warning | React(✅)VueNext（✅） ,Vue（✅）|
| t-tooltip-reference | 移除 | React(✅)VueNext（✅）,Vue（✅） |

**Comment by xiaosansiji** [comment]
Progress
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-progress--inner | t-progress__inner | Vue(✅ )、VueNext（✅ ）、React(✅) |
| t-progress--info | t-progress__info | Vue(✅ )、VueNext（✅）、React(✅) |
| t-progress--icon | t-progress__icon | Vue(✅ )、VueNext（✅）、React(✅) |
| t-progress--bar | t-progress__bar | Vue(✅ )、VueNext（✅）、React(✅) |
| t-circle--outer | t-progress__circle-outer | Vue(✅ )、VueNext（✅ ）、React(✅) |
| t-circle--inner | t-progress__circle-inner | Vue(✅ )、VueNext（✅ ）、React(✅) |

**Comment by xiaosansiji** [comment]
Radio
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-radio-group-outline | t-radio-group__outline | Vue(✅ )、VueNext（✅）、React(✅) |
| t-radio-group-filled | t-radio-group--filled | Vue(✅ )、VueNext（✅）、React(✅) |
| t-radio-group-filled-bg-block | t-radio-group__bg-block | Vue(✅ )、VueNext（✅）、React(✅ ) |
| t-radio-group-primary-filled | t-radio-group--primary-filled | Vue(✅ )、VueNext（✅）、React(✅) |
| t-radio-group-small | t-size-s | Vue(✅ )、VueNext（✅）、React(✅) |
| t-radio-group-medium | t-size-m | Vue(✅ )、VueNext（✅）、React(✅) |
| t-radio-group-large | t-size-l | Vue(✅ )、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Steps

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-steps-item-content | t-steps-item__content | x |
| t-steps-item-title | t-steps-item__title | x |
| t-steps-item-icon | t-steps-item__icon | x |
| t-steps-item-description | t-steps-item__description | x |
| t-steps-item-canclick | t-steps-item--clickable | x |
| default-step-icon | t-steps__default-icon | x |

**Comment by xiaosansiji** [comment]
TimePicker

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-time-picker-panel__container | t-time-picker__panel-container | Vue(✅ )、VueNext（✅）、React(✅) |
| t-time-picker-panel | t-time-picker__panel | Vue(✅)、VueNext（✅）、React(✅) |
| t-time-picker-panel__body | t-time-picker__panel-body | Vue(✅)、VueNext（✅）、React(✅) |
| t-time-picker-panel-section | t-time-picker__panel-section | Vue(✅ )、VueNext（✅）、React(✅) |
| t-time-picker-panel-section__body | t-time-picker__panel-section-body | Vue(✅ )、VueNext（✅）、React(✅) |
| t-time-picker-panel-section__footer | t-time-picker__panel-section-footer | Vue(✅ )、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Transfer

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-transfer-list | t-transfer__list | x |
| t-transfer-list-source | t-transfer__list-source | x |
| t-transfer-list-target | t-transfer__list-target | x |
| t-transfer-list__header | t-transfer__list-header | x |
| t-transfer-list__body | t-transfer__list-body | x |
| t-transfer-list-with-search | t-transfer__list--with-search | x |
| t-transfer-list-search-wrapper | t-transfer__search-wrapper | x |
| t-transfer-list__content | t-transfer__list-content | x |
| t-transfer-list__item | t-transfer__list-item | x |
| t-transfer-list__wrapper | t-transfer__list-wrapper | x |
| t-transfer-list__pagination | t-transfer__list-pagination | x |
| t-transfer-list__footer | t-transfer__list-footer | x |
| t-transfer-operations | t-transfer__operations | x |
| t-transfer-search | t-transfer__search | x |
| t-transfer-with-tree  | t-transfer--with-tree  | x |
| t-transfer-pagination | t-transfer__pagination | x |
| t-transfer-footer | t-transfer__footer | x |
| t-transfer-wrapper | t-transfer__wrapper | x |

**Comment by xiaosansiji** [comment]
Tree
| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-tree--fx | t-tree--transition | Vue(✅)、VueNext（✅）、React(✅) |
| t-tree-toggle-enter-active | t-tree__item--enter-active | Vue(✅)、VueNext（✅）、React(✅) |
| t-tree-toggle-leave-active | t-tree__item--leave-active | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by xiaosansiji** [comment]
Upload

| 原类名 | 新类名 | 是否已合入 develop |
|-----|-----|-----|
| t-upload-icon-delete | t-upload__icon-delete | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-list__file | t-upload__list-file | Vue(✅)、VueNext（无）、React(无) |
| t-upload-list__item | t-upload__list-item | Vue(✅)、VueNext（无）、React(无) |
| t-upload-list__name | t-upload__list-name | Vue(✅)、VueNext（无）、React(无) |
| t-upload-list__content | t-upload__list-content | Vue(✅)、VueNext（无）、React(无) |
| t-upload-list__controll | t-upload__list-controll | Vue(✅)、VueNext（无）、React(无) |
| t-upload-list__img | t-upload__list-img | Vue(✅)、VueNext（无）、React(无) |
| t-upload__highlight | t-upload--highlight | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-dialog | t-upload__dialog | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__mask-disabled | t-is-disabled | Vue(✅)、VueNext（✅）、React(无) |
| t-upload__small | t-size-s | Vue(✅)、VueNext（✅）、React(✅) |
| t-display-text--margin | t-upload__display-text--margin | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card-container | t-upload__card-container | Vue(✅)、VueNext（✅）、React(无) |
| t-upload-card | t-upload__card | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__item | t-upload__card-item | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__name | t-upload__card-name | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__content | t-upload__card-content | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__mask__item | t-upload__card-mask-item | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-card__status-wrap | t-upload__card-status-wrap | Vue(✅)、VueNext（✅）、React(无) |
| t-upload-card__content-border | t-is-bordered | Vue(✅)、VueNext（✅）、React(无) |
| t-upload-card__status | t-upload__card-status | Vue(✅)、VueNext（✅）、React(无) |
| t-upload-card__mask | t-upload__card-mask | Vue(✅)、VueNext（✅）、React(✅) |
| t-upload-dialog__body-img-box | t-upload__dialog-body-img-box | Vue(✅)、VueNext（✅）、React(✅) |

**Comment by Duncan-zjp** [comment]
改完了吗
