### ISSUE TITLE
希望css variables可以加上圆角

### ISSUE THREAD

**Issue by PsTiu** [Tencent/tdesign-common#398]
### 这个功能解决了什么问题

目前我们希望基于Tdesign中抽离的css variables去做样式定制，以符合自身品牌的设计规范。
设计师设计的样式中组件有圆角，但目前Tdesign抽离出来的css variables未包含圆角样式。

### 你建议的方案是什么

建议加上圆角的css variables

**Comment by uyarn** [comment]
published 
tdesign-vue >=0.44.1
tdesign-vue-next >=0.18.1
tdesign-react >=0.37.1
