### ISSUE TITLE
[Select] 本地启动dev-server的时候docs.css出现404，组件样式错乱

### ISSUE THREAD

**Issue by funczh** [Tencent/tdesign-common#550]
### tdesign-common 版本

1.0.0

### 重现链接

http://0.0.0.0:9000/components/select/

### 重现步骤
运行环境： macOS Monterey 12.4  Chrome 102.0.5005.61
1. git clone tdesign-common项目到本地
2. git submodule init && git submodule update
3. 安装主工程和子工程的依赖
4. 进入/style/web目录，运动npm start
5. 访问 http://0.0.0.0:9000/components/select/，看到页面上select组件样式错乱
6. 打开开发者调试工具，发现docs.css是404状态

### 期望结果

正常展示样式，可进行HTML和CSS编辑调整

### 实际结果

![image](https://user-images.githubusercontent.com/16182130/174510647-8f3847fb-a5db-42dd-84b2-c4685d7eddde.png)

**Comment by uyarn** [comment]
目前已经不再维护这个仓库的UI开发部分 开发模式为某框架发起UI+逻辑开发 然后再以此标准同步到其他框架
