### ISSUE TITLE
[Tree] Tree 的改动，单侧失败也合并了，导致 3 个框架的都有问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-common#652]
### tdesign-common 版本

无版本

### 重现步骤

<img width="776" alt="image" src="https://user-images.githubusercontent.com/11605702/179386364-e55b0467-b041-4db6-9f38-1ed705793afd.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/11605702/179386410-55406495-78d2-490e-81a1-1645b93d4b4a.png">

**Comment by chaishi** [comment]
@ardor-zhang

**Comment by ardor-zhang** [comment]
收到，正在处理中

**Comment by zhangpaopao0609** [comment]
> @ardor-zhang

这是在修复 https://github.com/Tencent/tdesign-vue-next/issues/1205 这个 issue 时更改 setData 导致的。

**目前的结论是：已经快速回滚了这个 commit**

更多的细节可查看：https://github.com/Tencent/tdesign-common/issues/655
