### ISSUE TITLE
文档翻译

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-common#788]
### 这个功能解决了什么问题

官网文档示例和设计指南部分的翻译工作

### 你建议的方案是什么

参照现有 Button 目录，增加 xx.en-US.md 文件，根据已有中文文档进行翻译工作，参见：https://github.com/Tencent/tdesign-common/blob/develop/docs/web/api/button.en-US.md

请在 issue 评论区说明自己想要认领的组件，并尽早提交 PR

验证方式：在本仓库 (tdesign-common) 提交 PR 后，请在 [tdesign-vue](https://github.com/Tencent/tdesign-vue) 也发起一个 PR，CI 全部通过后会有机器人评论本次 PR 合入后官网的预览地址：https://github.com/Tencent/tdesign-vue/pull/1408
![image](https://user-images.githubusercontent.com/7600149/187403053-5c4f6576-7795-48b0-9cc9-6a5275e9db62.png)
以已完成的 Button 为例，访问官网地址 https://tdesign.tencent.com/vue/components/button-en 可以查看到官网切换到英文时的效果：
![image](https://user-images.githubusercontent.com/7600149/187403520-1a7e9d4a-0c4c-4fce-8e22-c640465a986d.png)

组件认领列表：
### 基础

* [x] `button`- #472
* [x] `divider`  @vapourma
* [x] `icon` @vapourma

### 布局

* [x] `grid` @vapourma
* [x] `layout`  @vapourma

###  导航

* [x] `affix` @Tomaolala
* [x] `anchor`  @Tomaolala
* [x] `breadcrumb` @GolderBrother
* [x] `dropdown` @GolderBrother
* [x] `menu` @GolderBrother
* [x] `pagination` @GolderBrother
* [x] `steps` @vapourma
* [x] `tabs` @yangchao987
 

### 输入

* [x] `cascader ` @GolderBrother
* [x] `checkbox` @GolderBrother
* [x] `color-picker` @GolderBrother
* [x] `date-picker` @GolderBrother 
* [x] `form` @GolderBrother 
* [x] `input` @yangchao987
* [x] `input-number` @GolderBrother 
* [x] `radio` @yangchao987
* [x] `select` @GolderBrothe
* [x] `select-input`  @GolderBrother 
* [x] `slider` @GolderBrother 
* [x] `switch` @GolderBrother 
* [x] `tag-input` @GolderBrother 
* [x] `textarea` @GolderBrother 
* [x] `transfer` @GolderBrother 
* [x] `time-picker` @GolderBrother 
* [x] `tree-select`@GolderBrother 
* [x] `upload` @GolderBrother 

### 数据展示

* [x]  `avatar`  @Tomaolala
* [x]  `badge` @vapourma
* [x] `calendar` @vapourma
* [x] `card`  @yangchao987
* [x] `collapse ` @vapourma
* [x] `comment` @vapourma
* [x] `list` @vapourma
* [x] `loading` @xiaosansiji 
* [x] `progress` @vapourma
* [x] `skeleton` @vapourma
* [x] `swiper` @vapourma
* [x] `table` @vapourma
* [x] `tag` @vapourma
* [x] `tooltip`@vapourma
* [x] `tree`@vapourma

### 消息提醒

* [x] `alert` @Tomaolala
* [x] `dialog` @Tomaolala
* [x] `drawer` @GolderBrother
* [x] `message` @GolderBrother
* [x] `notification`  @GolderBrother
* [x] `pop-confirm` @GolderBrother
* [x] `popup`  @GolderBrother

**Comment by Tomaolala** [comment]
认领  affix/anchor/avatar/alert/config-provider/dialog @xiaosansiji  预计 9.2-9.3完成

**Comment by yangchao987** [comment]
认领 tabs/radio/card/input @xiaosansiji 预计 9.5-9.6完成

**Comment by GolderBrother** [comment]
认领 breadcrumb、dropdown、menu、pagination @xiaosansiji 预计 3-27~3-28完成

**Comment by GolderBrother** [comment]
认领 drawer、message、notification、pop-confirm、popup，@xiaosansiji  预计 4-6~4-7 完成

**Comment by vapourma** [comment]
认领3.31~4.20完成
select/select-input/slider/switch/tag-input/textarea/transfer/time-picker/tree-select/upload

**Comment by vapourma** [comment]
认领3.31~4.30完成
collapse/comment/list/loading/progress/skeleton/swiper/table/tag/tooltip/tree

**Comment by GolderBrother** [comment]
认领 cascader、checkbox、color-picker、date-picker、form、input-number、select、select-input、slider、switch、tag-input、textarea、transfer、time-picker、tree-select、upload，[@xiaosansiji](https://github.com/xiaosansiji) 预计 4-10~4-14 完成

**Comment by fengyingkong** [comment]
认领divider、icon、grid、layout、steps @xiaosansiji 预计4-10完成

**Comment by vapourma** [comment]
新增数据展示组件文档 #1292

**Comment by vapourma** [comment]
新增数据展示类英文组件文档 #1293
请忽视分支 #1292

**Comment by xiaosansiji** [comment]
感谢大家的支持，所有组件 demo 页相关的翻译工作都已经完成
