### ISSUE TITLE
[BreadCrumb] API 文档（类型定义） typo

### ISSUE THREAD

**Issue by Yilun-Sun** [Tencent/tdesign-common#95]
位置：breadcrumb -> type.ts
```JavaScript
/**
 * 最大宽度，超出后会以省略号形式呈现。优先级高于 Breadcrum 中的 maxItemWidth
 */
maxWidth?: string;
```
`Breadcrum` 应为 `Breadcrumb`

⚠️ 此问题为共性问题，应该在 React、Vue 和 Vue Next 中都又出现。

**Comment by uyarn** [comment]
@chaishi have a look~

**Comment by chaishi** [comment]
![image](https://user-images.githubusercontent.com/11605702/148923715-943943aa-5ad5-41d0-b96d-92bc9845437e.png)

看了下，数据源已经改了，各框架 CLI 更新一下就好

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue/pull/219

**Comment by chaishi** [comment]
解释一下共性问题的原因：每个框架的文档，数据来源都是同一个地方，一个有问题，另一个也会有问题。

同样的，数据源修复了，其他的框架更新即可修复
