### ISSUE TITLE
使用子仓库方式引入的考量是什么

### ISSUE THREAD

**Issue by heng1025** [Tencent/tdesign-common#96]
为啥不考虑npm package

**Comment by richerfu** [comment]
样式是多版本（react vue ng 移动端等）共用。monorepo维护更麻烦吧..

**Comment by chaishi** [comment]
想起了一群一堆喷大仓库的同学~~~

**Comment by LJJCherry** [comment]
关注～

**Comment by heng1025** [comment]
> 样式是多版本（react vue ng 移动端等）共用。monorepo维护更麻烦吧..

可以发布npm packages, 其他的项目作为依赖使用
